Portal - support tenant management
ctera/ctera-ansible-collections pull request #15
Opened 2021-01-21 20:02 UTC by ygalblum

Modify - only plan is supported

2021-01-21 21:21 UTC, saimonation commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +    - Whether the specified user should exist or not.
description indicates 'user'

2021-01-21 21:24 UTC, saimonation commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +            plans = self._ctera_portal.plans.list_plans(include=['name', 'baseObjectRef'])
This can be improved, we now support `Plans.plans.by_name`

2021-01-21 21:26 UTC, saimonation requested changes

2021-01-21 21:26 UTC, saimonation commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +            self._ctera_portal.portals.undelete(self.parameters['name'])
Question, so a tenant is automatically restored on update?

2021-01-21 21:27 UTC, ygalblum commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +    - Whether the specified user should exist or not.
Fixed

2021-01-21 21:28 UTC, ygalblum commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +            plans = self._ctera_portal.plans.list_plans(include=['name', 'baseObjectRef'])
This method looks for the plan's name based on its object ref. That's not what the "by_name" does. What am I missing?

2021-01-21 21:31 UTC, ygalblum commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +            self._ctera_portal.portals.undelete(self.parameters['name'])
If the state is "present", we need to make sure it is available. The tenant can either not exists at all and then we will create it, can exist and Enabled in which case we only check if we need to modify and it can be Disabled, in which case it will be undeleted.
Please note that the Ansible module never deletes forever (also the SDK does not support it). If we wanted we could have the state hold more options - Enabled/Disabled/Deleted and then handle it accordingly.

2021-01-21 22:47 UTC, saimonation commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +            plans = self._ctera_portal.plans.list_plans(include=['name', 'baseObjectRef'])
Oh I see. Then base_object_ref are "gettable" you can simply use `self._ctera_portal.get(plan_object_ref)`

2021-01-21 22:49 UTC, saimonation commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +            self._ctera_portal.portals.undelete(self.parameters['name'])
Got it. So on modify, disabled tenants are restored. Ok that makes sense.

2021-01-21 23:38 UTC, ygalblum commented on ansible_collections/ctera/ctera/plugins/modules/ctera_portal_tenant.py
> +            plans = self._ctera_portal.plans.list_plans(include=['name', 'baseObjectRef'])
Done

2021-01-22 00:11 UTC, saimonation approved these changes

2021-01-22 13:45 UTC, merged